### ISSUE TITLE
Attachments post parent

### ISSUE THREAD

**Issue by garethhorner** [houke/color-palette-generator#3]
Hey man
Happy New Year!
Is possible to the get the parent post link of an attachment - to replace the link to the attachment page in search results? 
Ideally the ability to bring in associated custom fields too?
Thanks again in advance
Gareth

**Comment by houke** [comment]
Hi,

Right now, search results do indeed return the attachment page permalink. If you have a look at the templates/search.php file you'll see something like:

`get_permalink( get_the_ID() );`

**Untested:**
Instead of that, you can get the post parent via 
`wp_get_post_parent_id( get_the_ID() );`

Now you have the ID of the parent, so you can get it's meta fields as well.

You can create a templates folder in your (child) theme and add the search.php file there, so you don't have to edit core plugin files.

**Comment by garethhorner** [comment]
Amazing, that worked perfectly — appending '$post->post_parent' to an echo brought in the related fields. Thank you again!

**Comment by houke** [comment]
Perfect!
